name: procastiless
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.3.0+3

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.1
  fluro: ^2.0.5
  firebase_core: "^2.16.0"
  firebase_auth: ^4.10.0
  google_fonts: ^6.1.0 
  google_sign_in: ^6.1.5
  cloud_firestore: ^4.9.2
  carousel_slider: ^4.0.0
  flutter_slidable: ^3.0.0
  http: ^1.1.0
  checkmark: ^0.0.2+1
  equatable: ^2.0.3
  shimmer: ^2.0.0
  file: ^6.1.4
  url_launcher: ^6.0.20
  tutorial_coach_mark: ^1.2.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  animated_text_kit: ^4.2.2
  calendar_appbar: ^0.0.5
  shared_preferences: ^2.0.15
  flutter_launcher_icons: ^0.11.0
  fluttertoast: ^8.1.2
  foundation_flutter: ^0.2.0
  firebase_analytics: ^10.5.1
  confetti: ^0.7.0
  uuid: ^3.0.7
  in_app_purchase: ^3.1.11
  bloc_test: ^8.0.0
  mockito: ^5.4.2
  smooth_page_indicator: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ic_launcher.png"
  min_sdk_android: 21
  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/Characther.png    
    - assets/images/char1.png
    - assets/images/char2.png
    - assets/images/char3.png
    - assets/images/next.png
    - assets/images/bell.png
    - assets/images/bell1.png
    
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Black.ttf
        - asset: fonts/Poppins-BlackItalic.ttf
          style: italic
        - asset: fonts/Poppins-Bold.ttf
        - asset: fonts/Poppins-BoldItalic.ttf
        - asset: fonts/Poppins-ExtraBold.ttf
        - asset: fonts/Poppins-ExtraBoldItalic.ttf
        - asset: fonts/Poppins-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
